namespace: "nanodayo"
name: "ansible_twitter"
version: "1.0.0"
description: "module for twitter."
authors:
  - "Daisuke Matsui <nanodayo.work@gmail.com>"
license:
  - "Apache-2.0"
readme: README.md
tags: []
dependencies: {}
repository: https://github.com/nanodayo/ansible_twitter_module
